#!/usr/bin/env bash
# Generate a real .env for KP2 -- a random token PIN and admin password.
# .env.example ships placeholders that cannot work on purpose
# (docs/reviews/2026-07-28-branch-review.md finding S2); this is the only
# thing that should ever write a working .env.
#
#   scripts/gen-secrets.sh          # refuses if .env already exists, UNLESS
#                                    # it is only missing keys this script
#                                    # added after it was written (below), in
#                                    # which case it appends just those
#   scripts/gen-secrets.sh --force  # overwrites -- see the PIN-rotation
#                                    # warning this prints first
#
# .env is sourced directly by scripts/lib-stack.sh (`set -a; . .env`), not passed
# through a quoting layer, so the generated values must be safe to sit
# unquoted on the right-hand side of a shell assignment: no $, backtick,
# quote, backslash or whitespace (breaks the assignment itself), and no
# other shell metacharacter that has meaning outside a quoted string either
# (; & | < > ( ) ~ end the assignment or trigger expansion the same way).
# The alphabet below is deliberately narrower than that minimum -- letters,
# digits, and a small set of punctuation with no meaning to bash in this
# position at all -- rather than enumerate every character that happens to
# be safe today.
set -euo pipefail
PACK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$PACK_DIR/.env"
ALPHABET='A-Za-z0-9@%+_.-'

# `head -c 24` exiting once it has enough bytes sends tr SIGPIPE on its next
# write -- normal and expected, but a non-zero exit from tr under `set -o
# pipefail` would otherwise abort the script right here. Found live: this
# failed intermittently (worked for the PIN, failed for the password, same
# command, same run) before this fix.
random_value() {
  local value
  set +o pipefail
  value=$(LC_ALL=C tr -dc "$ALPHABET" < /dev/urandom | head -c 24)
  set -o pipefail
  printf '%s' "$value"
}

# KP2_JOIN_APPLICANT_TOKEN/KP2_JOIN_OPERATOR_TOKEN were added to this
# script's own output after some .env files were already generated
# (join-b). docker-compose.yml now requires both unconditionally at
# interpolation time (${VAR:?...}), even for services in the demo profile
# that nobody is bringing up -- so an .env that predates them breaks the
# WHOLE pack, not just the join-related parts, until it has them. Below: if
# that is the ONLY thing wrong with an existing .env, append just those two
# keys rather than refusing outright --
# no PIN/password rotation, so none of the --force path's teardown/purge
# warning applies.
JOIN_TOKEN_KEYS="KP2_JOIN_APPLICANT_TOKEN KP2_JOIN_OPERATOR_TOKEN"

if [ -f "$ENV_FILE" ] && [ "${1:-}" != "--force" ]; then
  missing=""
  for key in $JOIN_TOKEN_KEYS; do
    grep -q "^${key}=" "$ENV_FILE" || missing="$missing $key"
  done
  if [ -z "$missing" ]; then
    echo "gen-secrets.sh: $ENV_FILE already exists -- refusing to overwrite it." >&2
    echo "Pass --force to regenerate it (prints a warning first -- read it)." >&2
    exit 1
  fi
  echo "gen-secrets.sh: $ENV_FILE exists and already has everything except:$missing" >&2
  echo "-- appending only those (no PIN/password rotation, nothing else touched)." >&2
  for key in $missing; do
    printf '%s=%s\n' "$key" "$(random_value)" >> "$ENV_FILE"
  done
  echo "gen-secrets.sh: appended$missing to $ENV_FILE." >&2
  exit 0
fi

if [ -f "$ENV_FILE" ]; then
  echo "gen-secrets.sh: WARNING -- overwriting $ENV_FILE." >&2
  echo "If a federation is already deployed, its software token was initialised" >&2
  echo "with the CURRENT pin. Changing it here does not change it on the token:" >&2
  echo "the mismatch produces X-Road errors that look like certificate faults," >&2
  echo "not PIN errors (docs/xroad-770-notes.md). If a federation is up, run" >&2
  echo "scripts/teardown.sh --purge and redeploy AFTER this, not before." >&2
fi

TOKEN_PIN=$(random_value)
ADMIN_PASSWORD=$(random_value)
JOIN_APPLICANT_TOKEN=$(random_value)
JOIN_OPERATOR_TOKEN=$(random_value)

cat > "$ENV_FILE" <<EOF
# KP2 build pack -- secrets only. Generated by scripts/gen-secrets.sh on
# $(date -u +%Y-%m-%dT%H:%M:%SZ). Never committed (.gitignore). Deployment
# shape lives in deployment.yaml, not here.
XROAD_TOKEN_PIN=$TOKEN_PIN
XROAD_ADMIN_USER=xrd
XROAD_ADMIN_PASSWORD=$ADMIN_PASSWORD
KP2_JOIN_APPLICANT_TOKEN=$JOIN_APPLICANT_TOKEN
KP2_JOIN_OPERATOR_TOKEN=$JOIN_OPERATOR_TOKEN
EOF
chmod 600 "$ENV_FILE"

echo "gen-secrets.sh: wrote $ENV_FILE (mode 600). Values are never printed here -- read the file directly if you need them."
