#!/usr/bin/env bash
# Regenerate both golden corpora (tests/golden/deployment/ and
# tests/golden/hosted-fixture/generated/) after an intended change to
# hurl/generate.py, its templates or steps.py.
#
# This was a manual multi-step ritual documented in hurl/README.md: run
# generate.py with --out/--env into a temp directory, rm -rf the corpus, cp
# the temp directory over it -- and then, for the hosted-fixture half, "let
# tests/test_golden.py build the temp copy, then cp -r its hosted-fixture-out/
# over the corpus before the temp directory is cleaned up (pytest --pdb or a
# manual copy of the function body both work)". A regeneration path that is
# easier to get wrong than to skip is one that gets skipped, and a skipped
# regeneration is a golden test that fails on the next unrelated change.
#
# The hosted-fixture half calls tests/test_golden.py's own
# _generate_hosted_fixture() rather than reimplementing the
# copy-generate.py-into-a-temp-pack mechanism in bash. That is the point: the
# corpus is then regenerated by exactly the code that verifies it, so the two
# cannot drift into disagreeing about how the fixture pack is built.
#
# It deliberately does NOT commit anything. A golden corpus updated without
# reading the diff is theatre, not a test -- so this prints the diffstat and
# stops.
set -euo pipefail

PACK_DIR=$(cd "$(dirname "$0")/.." && pwd)
cd "$PACK_DIR"

log() { printf '\033[1;34m[regen-golden]\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31m[regen-golden FAIL]\033[0m %s\n' "$*" >&2; exit 1; }

# The venv, for the same reason scripts/verify.sh uses it: _generate_hosted_fixture()
# imports pytest. generate.py itself still runs under the host python3 below,
# which is what the golden corpus is a corpus OF.
PY="$PACK_DIR/.venv/bin/python3"
[ -x "$PY" ] || fail "no .venv -- run scripts/verify.sh --fast once to build it."

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

log "deployment corpus"
python3 hurl/generate.py --out "$TMP/deployment" --env tests/golden/env.fixture

log "hosted-fixture corpus"
"$PY" - "$TMP" <<'PY'
import pathlib, sys
sys.path.insert(0, "tests")
from test_golden import _generate_hosted_fixture
out = _generate_hosted_fixture(pathlib.Path(sys.argv[1]))
print(out)
PY

rm -rf tests/golden/deployment tests/golden/hosted-fixture/generated
cp -r "$TMP/deployment" tests/golden/deployment
cp -r "$TMP/hosted-fixture-out" tests/golden/hosted-fixture/generated

log "verifying the regenerated corpora"
"$PY" -m pytest tests/test_golden.py -q || fail "the golden test still fails against the corpus this just wrote -- generate.py is not deterministic, or one of the two corpora was written from the wrong source."

log "regenerated. READ THIS DIFF before committing it:"
git --no-pager diff --stat -- tests/golden/ || true
echo
log "nothing was committed. A corpus updated without reading the diff is theatre, not a test."
