"""scripts/render_path_conformance.py -- renders docs/path-conformance.md
from docs/path-conformance.yaml.

Why a generated file rather than a hand-written status section: on 2026-08-08
an external review found three findings recorded as closed by
`configs/governance/governance.yaml` and a BB pattern register in
`join-policy.yaml`, neither of which had ever been created. Both claims sat in
prose, in two different documents, and nothing could contradict them. The
mechanism that would have caught it is not better prose -- it is making the
status machine-readable and its evidence existence-checked, which is what
docs/path-conformance.yaml plus tests/test_path_conformance.py do.

So: this script never decides anything. It reads the YAML and lays it out.
Every judgement lives in the YAML, next to the evidence that has to exist for
the judgement to survive `verify.sh --fast`.

Usage:
    python3 scripts/render_path_conformance.py           # write the .md
    python3 scripts/render_path_conformance.py --check   # exit 1 if stale

`--check` is what the test and the ship gate run: a YAML edit that was not
re-rendered is a failure, on the same "generated, never hand-maintained" rule
writer.render_onboarding_tree() applies to onboarding/<key>/.
"""
from __future__ import annotations

import pathlib
import sys

import yaml

PACK = pathlib.Path(__file__).resolve().parent.parent
SOURCE = PACK / "docs" / "path-conformance.yaml"
TARGET = PACK / "docs" / "path-conformance.md"

# Order is the reading order of the path document, not alphabetical: a reader
# arrives here holding the path, and wants to walk it top to bottom.
SECTION_TITLES = [
    ("0", "§0 — What must exist before any member can be onboarded"),
    ("1", "§1 — The two-track shape"),
    ("1a", "§1a — Conventions to publish before G1"),
    ("G0", "G0 — Eligibility and intent"),
    ("G1", "G1 — Admission decision"),
    ("G2", "G2 — Hosting and topology decision"),
    ("G3", "G3 — Identity and trust"),
    ("G4", "G4 — Platform conformance"),
    ("G5", "G5 — Service conformance and registration"),
    ("G6", "G6 — Production go-live and handover"),
    ("GX", "GX — Retirement"),
    ("3", "§3 — The technical sequence inside G4–G5"),
    ("4", "§4 — What can be automated, and what cannot"),
    ("6", "§6 — The operator's own building blocks"),
    ("6a", "§6a — Building blocks and the semantic layer"),
    ("7", "§7 — The onboarding file"),
]

STATUS_LABEL = {
    "implemented": "implemented",
    "simulated": "simulated",
    "named-absence": "named absence",
    "out-of-scope": "out of scope",
}

STATUSES = tuple(STATUS_LABEL)

HEADER = """\
# Conformance against the member onboarding path

<!-- GENERATED by scripts/render_path_conformance.py from
     docs/path-conformance.yaml. Do not edit this file: edit the YAML and
     re-render. tests/test_path_conformance.py fails if the two disagree, and
     fails if any cited evidence path does not exist. -->

**Path:** `{path_document}` ({path_version})
**Last reviewed:** {reviewed}

This is the only place the pack states its status against the path. Narrative
documents carry reasoning; where one of them also carries a status claim, treat
this file as authoritative — that divergence is what produced the corrections
dated 2026-08-08 in `docs/onboarding-alignment-design.md` and
`docs/onboarding-path-gap-analysis.md`.

**There is no tick mark here, deliberately.** A ✓ that meant "built" in one row
and "labelled" in the next is how a status table stops being readable. Four
statuses, and a clause that fits none of them is a defect rather than a fifth
status:

| Status | Means |
| --- | --- |
| **implemented** | A real artefact or check. If the pack broke it, something would fail. |
| **simulated** | Exercised for real, fidelity faked (Test CA, mock backends, synthetic data). Legitimate in a build pack; the declaration is part of the evidence. |
| **named absence** | Not built, and the pack says so where a reader following it will meet the absence. |
| **out of scope** | Deliberately not this pack's job, with a stated reason. |

"""


def load() -> dict:
    return yaml.safe_load(SOURCE.read_text())


def _summary(clauses: list[dict]) -> str:
    counts = {s: 0 for s in STATUSES}
    for clause in clauses:
        counts[clause["status"]] += 1
    total = len(clauses)
    rows = "".join(
        f"| {STATUS_LABEL[s]} | {counts[s]} | {counts[s] * 100 // total}% |\n" for s in STATUSES
    )
    return f"## Summary\n\n| Status | Clauses | Share |\n| --- | ---: | ---: |\n{rows}| **total** | **{total}** | |\n\n"


def _open_defects(clauses: list[dict]) -> str:
    """A named absence is a teaching device; an open defect is not. The YAML
    marks the difference in prose, so surface it rather than making a reader
    scan sixty rows for the word."""
    defects = [c for c in clauses if "OPEN DEFECT" in (c.get("note") or "")]
    if not defects:
        return ""
    lines = "".join(f"- **{c['id']}** — {c['clause']}\n" for c in defects)
    return (
        "## Open defects\n\n"
        "Absences the pack has not decided to accept — distinct from the named\n"
        "absences below, which are deliberate and carry their lesson:\n\n"
        f"{lines}\n"
    )


def _evidence(clause: dict) -> str:
    parts = []
    for item in clause["evidence"]:
        symbol = item.get("symbol")
        parts.append(f"`{item['path']}`" + (f" (`{symbol}`)" if symbol else ""))
    return "<br>".join(parts)


def _cell(text: str | None) -> str:
    """Table cells are one line; the YAML's folded scalars are not."""
    return " ".join((text or "").split()).replace("|", "\\|")


def render(doc: dict) -> str:
    clauses = doc["clauses"]
    meta = doc["meta"]
    out = [HEADER.format(**meta), _summary(clauses), _open_defects(clauses)]

    by_section: dict[str, list[dict]] = {}
    for clause in clauses:
        by_section.setdefault(str(clause["section"]), []).append(clause)

    for key, title in SECTION_TITLES:
        rows = by_section.pop(key, [])
        if not rows:
            continue
        out.append(f"## {title}\n\n")
        out.append("| # | Clause | Status | Note | Evidence |\n| --- | --- | --- | --- | --- |\n")
        for clause in rows:
            note = _cell(clause.get("note") or clause.get("rationale"))
            out.append(
                f"| {clause['id']} | {_cell(clause['clause'])} | "
                f"**{STATUS_LABEL[clause['status']]}** | {note} | {_evidence(clause)} |\n"
            )
        out.append("\n")

    if by_section:
        # A section in the YAML with no title here would be silently dropped,
        # which is the same class of bug this whole file exists to prevent.
        raise SystemExit(
            "render_path_conformance.py: clauses in unknown section(s) "
            f"{sorted(by_section)} -- add them to SECTION_TITLES"
        )

    out.append(
        "---\n\n"
        f"Regenerate with `python3 {meta['generator']}`. "
        f"`{meta['test']}` proves every path above exists and every symbol resolves.\n"
    )
    return "".join(out)


def main() -> None:
    rendered = render(load())
    if "--check" in sys.argv[1:]:
        current = TARGET.read_text() if TARGET.exists() else ""
        if current != rendered:
            raise SystemExit(
                f"render_path_conformance.py: {TARGET.relative_to(PACK)} is stale -- "
                f"run `python3 {SOURCE.parent.parent.name and 'scripts/render_path_conformance.py'}`"
            )
        print(f"{TARGET.relative_to(PACK)} is up to date")
        return
    TARGET.write_text(rendered)
    print(f"rendered {TARGET.relative_to(PACK)}")


if __name__ == "__main__":
    main()
