# GENERATED by hurl/generate.py -- do not hand-edit.
# One topology, generated once: scripts/lib.sh sources this instead of
# declaring these four itself; apps/console reads the same generation
# run's hurl/topology.json. Regenerate with: python3 hurl/generate.py

declare -A SS_UI=(
  [ss-pdga]=1000
  [ss-pnea]=2000
  [ss-plr]=3000
)
declare -A SS_REST=(
  [ss-pdga]=1080
  [ss-pnea]=2080
  [ss-plr]=3080
)
SS_ORDER=(ss-pdga ss-pnea ss-plr)
declare -A HOST_SS=(
  [PDGA:MANAGEMENT]=ss-pdga
  [PNIA:IDENTITY]=ss-plr
  [PLR:ENROLMENT]=ss-plr
  [MOEYS:PEMIS]=ss-plr
  [PNEA:EXAMS]=ss-pnea
)
